# Generated by Django 4.0.5 on 2022-06-28 19:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_VHT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Phone_Number', models.CharField(max_length=15)),
                ('DOB', models.DateField()),
                ('Reg_date', models.DateTimeField(auto_now=True)),
                ('NIN', models.CharField(max_length=20)),
                ('Village_or_Zone', models.CharField(max_length=20)),
                ('Parish_or_Ward', models.CharField(max_length=20)),
                ('SubCounty', models.CharField(max_length=20)),
                ('District', models.CharField(choices=[('Kampala', 'Kampala'), ('Arua Central', 'Arua Central '), ('Koboko', 'Koboko')], default='Kampala', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Register_People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UPIDN', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(default='Male', max_length=10, verbose_name=[('Male', 'Male'), ('Female', 'Female')])),
                ('Date_Of_Birth', models.DateField(max_length=10)),
                ('Village_or_Zone', models.CharField(max_length=30)),
                ('Parish_or_Ward', models.CharField(max_length=30)),
                ('SubCounty', models.CharField(max_length=30)),
                ('City_or_Municipality', models.CharField(max_length=30)),
                ('Status', models.CharField(default='Alive', max_length=10, verbose_name=[('Dead', 'Dead'), ('Alive', 'Alive')])),
                ('Attach_BirthCertificate', models.ImageField(upload_to='Birth_Certificates')),
                ('Father_Name', models.CharField(max_length=20)),
                ('Mother_Name', models.CharField(max_length=20)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VHT.register_vht')),
            ],
        ),
    ]
