# Generated by Django 4.0.5 on 2022-06-29 15:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('VHT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_vht',
            name='VHTIDN',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
